In [7]:
from numpy.random import randint
import numpy as np

In [2]:
def generate_formula(k, n, v):
    '''
    Generate boolean formula in conjunctive normal form.
    :param k: number of literals in clause
    :param n: number of clauses
    :param v: number of variables
    :return: Lists of lists. Each smaller list means the clause.
    Value represents variable index, negative value means a negation of the value.
    '''
    formula = []
    for i in range(n):
        clause = []
        for j in range(k):
            literal = randint(1, v+1)
            negative = randint(2)
            if negative:
                literal = -literal
            clause.append(literal)
        formula.append(clause)
    return formula

In [9]:
fla = generate_formula(2, 3, 5)

In [10]:
fla

[[1, -4], [1, 1], [2, -4]]

In [22]:
np.abs(fla)

array([[1, 4],
       [1, 1],
       [2, 4]])

In [21]:
0 & 1

0

In [15]:
np.random.choice(s_ar, 5)

array([ True, False,  True,  True,  True], dtype=bool)

In [38]:
def evaluate_clause(cl):
    return max(cl)==1

In [123]:
def solve_sat(formula, m):
    '''
    Randomized SAT implementation.
    :param formula: formula in generate_formula function result format
    :param m: Maximum number of iterations
    :return: boolean valuse - formula satisfiability
    '''
    # %%% START YOUR CODE HERE %%%
#     pass
    s_ar = np.array([-1, 1], dtype=np.int8)
    v = np.abs(formula).max()
    init = np.random.choice(s_ar, v)
    print(formula)
    print(init)
    for i in range(m):
        sat=True
        for row in formula:
            clause = [np.sign(i)*init[np.abs(i)-1] for i in row]
            if(not evaluate_clause(clause)):
                init[np.abs(np.random.choice(row,1))-1] *= -1
                sat=False
                break
        if sat==True:
            return init
    print('Failed')
    # %%% END YOUR CODE HERE %%%

In [137]:
solve_sat(fla,2)

[[1, -4], [1, 1], [2, -4]]
[-1  1 -1  1]
Failed


In [30]:
np.sign(1)

1